"""initial

Revision ID: fc38e427eabb
Revises: 
Create Date: 2024-09-28 02:51:16.810919

"""
from typing import Sequence, Union
import os

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType
from fastapi_storages import FileSystemStorage

from src.config import settings

storage_path = os.path.join(settings.MEDIA_DIR, 'signboard')
os.makedirs(storage_path, exist_ok=True)

# revision identifiers, used by Alembic.
revision: str = 'fc38e427eabb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signboard',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('access_token', sa.String(), nullable=False, comment='Уникальный номер'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False, comment='Email'),
                    sa.Column('password', sa.String(length=255), nullable=False, comment='Пароль'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('signboard_item',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('signboard_id', sa.Integer(), nullable=False),
                    sa.Column('file', FileType(storage=FileSystemStorage(path=storage_path)), nullable=True,
                              comment='Файл вывески'),
                    sa.Column('height', sa.Integer(), nullable=False, comment='Высота в мм'),
                    sa.Column('width', sa.Integer(), nullable=False, comment='Ширина в мм'),
                    sa.ForeignKeyConstraint(['signboard_id'], ['signboard.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signboard_item')
    op.drop_table('user')
    op.drop_table('signboard')
    # ### end Alembic commands ###
